name: Static analysis of php-graph-sdk
on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: Run PHPCS
        run: ./vendor/bin/phpcs
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
        env:
          FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
